### ISSUE TITLE
Allow for channels with different port names in different partitions

### ISSUE THREAD

**Issue by dadada** [DLR-FT/a653rs-linux#93]
A partition cannot be configured to receive the same data from channels with source ports that have the same name.

## Why?

If there are two ports providing the same data from different partitions, the ports at the source -side may (likely) have the same names. For the Linux hypervisor this means that the destination ports must have the same names as the respective source ports, defined by the channel's `name`. However, it is not possible to create these two destination ports with the same name in the destination partition, since partition names must be unique within the same partition.

## Proposed solution

The destinations and sources of sampling and queuing channels should be identified by pairs of partition names and port names. The port names only need to be unique within the partition. This should be possible:

```yaml
channel:  
  - !Sampling
    name: "CasHAdvisory"
    msg_size: 1000
    source: [ cas, "HvAdvisory" ]
    destination: 
      - [ router, "CasHvAdvisory" ]

  - !Sampling
    name: "ImageRecognitionAdv"
    msg_size: 1000
    source: [ image_recognition, HvAdvisory ]
    destination: 
      - [ router, "IRHvAdvisory" ]
```
